### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by kazumaxneo** [junhaiqi/centroAnno#1]
Hi,

centroAnno seems very fast and I would like to use my genome assembly.  
But test commnad failed with error messages.

$ ./centroAnno example/cen21.fa -o example/test  
Sequence Length: 331149  
Illegal instruction (core dumped)  

Enviroment  
Ubuntu 22.04  
compiled with g++ 7.4.0

**Comment by junhaiqi** [comment]
> Hi,
> 
> centroAnno seems very fast and I would like to use my genome assembly. But test commnad failed with error messages.
> 
> $ ./centroAnno example/cen21.fa -o example/test Sequence Length: 331149 Illegal instruction (core dumped)
> 
> Enviroment Ubuntu 22.04 compiled with g++ 7.4.0

Thank you very much for your attention to centroAnno. This problem does not occur in my environment, you can try compiling with a higher version of g++ (such as g++ 9.4.0). Here are my command lines:

1. git clone https://github.com/junhaiqi/centroAnno.git && cd centroAnno

2. make -j8

3. ./centroAnno example/cen21.fa -o example/test
    Output: 

    Sequence Length: 331149
    Clustering is over, there are 12 templates. There are 0 templates are filtered.
    Number of bad regions: 0
    Too many bad blocks were found, reinfer monomer templates and redecompose...
    Most frequent HOR length (monomer sequence) is: 11

My g++ version is 9.4.0. 

g++ -v:

Output:

    Using built-in specs.
    COLLECT_GCC=g++
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
    OFFLOAD_TARGET_NAMES=nvptx-none:hsa
    OFFLOAD_TARGET_DEFAULT=1
    Target: x86_64-linux-gnu
      Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by kazumaxneo** [comment]
Dear junhaiqi

Thank you the reply.
I upgraded g++ and recompiled with g++  9.4.0 or more newer version. 
But same error cotinues to happpen.
If possible, could you please deposit the pre-compiled binaries in the release ?

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by junhaiqi** [comment]
Hi,

Thank you again for your attention to centroAnno. If possible, you can try to recompile it on another machine to see if it works. We have uploaded the compiled centroAnno, you can check whether it works.

**Comment by kazumaxneo** [comment]
Dear  junhaiqi

Thank you for the reply.
I tried  using three Ubuntu installed  machine, but all crashs with same error messeges.

Machine1: TR5995WX, ubuntu22.04
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

Machine2: xeon E5 v4 dual, , ubuntu22.04
g++ (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0

Machine3: TR3990WX
g++ (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0

Then I checked shard libraries.
ldd ./centroAnno 
	linux-vdso.so.1 (0x00007ffea85b4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x000072d459755000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x000072d459400000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000072d45966e000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x000072d4593b6000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000072d45964e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000072d459000000)
	/lib64/ld-linux-x86-64.so.2 (0x000072d45982d000)
and used gdb to see the detail of error.

(gdb) run example/cen21.fa -o example/test
Starting program: /home/kazu/Documents/centroAnno/centroAnno example/cen21.fa -o example/test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Sequence Length: 331149
[New Thread 0x7ffff7600640 (LWP 112806)]
[New Thread 0x7ffff6c00640 (LWP 112807)]
[New Thread 0x7ffff6200640 (LWP 112808)]
[New Thread 0x7ffff5800640 (LWP 112809)]
[New Thread 0x7ffff4e00640 (LWP 112810)]
[New Thread 0x7ffff4400640 (LWP 112811)]
[New Thread 0x7ffff3a00640 (LWP 112812)]

Thread 1 "centroAnno" received signal SIGILL, Illegal instruction.
0x00005555555a90cd in spoa::Graph::AddAlignment(std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) ()
(gdb) 

I noticed my spoa library was something strange so I recompiled spoa 

git clone --recursive https://github.com/rvaser/spoa.git
cd spoa
mkdir build
cd build
cmake -DCMAKE_CXX_FLAGS="-march=x86-64" ..
make -j8
cp lib/libspoa.a ~/Documents/centroAnno/lib/  

and recompiled centroAnno and looks like successfully worked.

![Image](https://github.com/user-attachments/assets/f519a68c-bb08-4835-8740-4228fe7a47fc)

Thank you very much.

**Comment by junhaiqi** [comment]
Thank you for sharing your process of solving the problem. We have updated README.md based on your sharing.

**Comment by justdx** [comment]
Hi Junhai,

Thank you for your reply!

I tried reinstalling centroAnno using conda. Although the installation appeared to complete successfully, unfortunately, I still encountered the same “Illegal instruction” error as before.

Do you have any thoughts on what might be causing this issue?

Best,
Xiao

**Comment by junhaiqi** [comment]
Hi Xiao,

Thank you for your feedback again. I'm also very confused about this issue. Can I recompile using a different machine, or use -O2 compilation optimization instead of -O3 (that is, replace CXXFLAGS = -std=c++11 -O3 -fopenmp -I./include -w in the Makefile with CXXFLAGS = -std=c++11 -O2 -fopenmp -I./include -w and then recompile)?

**Comment by junhaiqi** [comment]
Hi Xiao，

Is your problem solved? I guess the problem is still with libspoa.a. Have you tried using a more conservative compilation method to get libspoa.a?

Cmd:

```bash
git clone --recursive https://github.com/rvaser/spoa.git
cd spoa
mkdir build
cd build
cmake -DCMAKE_CXX_FLAGS="-O2 -march=core2 -mtune=generic" ..
make -j8
cp lib/libspoa.a ~/Documents/centroAnno/lib/
```
